#!/usr/bin/env bash

echo "#i> /proc/diskstats:"
cat /proc/diskstats \
    | awk '{ printf "%-10s %-10s %-10s %-10s %-15s %-10s %-10s %-10s %-10s %-10s %-10s\n", \
                     $1  , $2  , $3  , $4  , $5  , $6  , $7  , $8  , $9  , $10 , $11 }'

