pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["2d_graphics_tests.htm","2D Graphics Test","2D Graphics Test Top Previous Next This suite contains a number of tests that exercise Qt&#39;s QPainter graphics functions and the video card. The nu...",""],
["3d_graphics_test.htm","3D Graphics Test","3D Graphics Test Top Previous Next Tests the OpenGL&#39;s graphics system. This test creates and animates an OpenGL depth buffer with RGBA or color in...",""],
["advanced_options.htm","Advanced options","Advanced options Top Previous Next Maintaining multiple test configurations Report Information (Machine ID and Notes) Command Line Parameters Prep...",""],
["cd_rom_and_dvd_test.htm","Optical Drive Test","Optical Drive Test Top Previous Next Tests the CD-ROM, DVD and BluRay drives. This test can be used with many different types of CD / DVD media, i...",""],
["cd_rom_dvd_preferences.htm","CD-ROM/DVD Preferences","CD-ROM/DVD Preferences Top Previous Next CD-ROM/DVD test preferences CD/DVD Selection and test method These fields allow the user to select the CD...",""],
["command_line_parameters.htm","Command Line Parameters","Command Line Parameters Top Previous Next -C configname BurnInTest will load the config file specified. -D duration Sets the test duration to the ...",""],
["command_line_version.htm","Command Line Version","Command Line Version Top Previous Next The command line version of BurnInTest does not have a Graphical User Interface and as such does not requir...",""],
["common_error_messages.htm","Common Error Messages","Common Error Messages Top Previous Next When BurnInTest encounters an error during a test run a short description of the error is displayed in the...",""],
["contacting_passmark_software.htm","Contacting PassMark Software","Contacting PassMark Software Top Previous Next On the Web You can contact PassMark on the web at: http://www.passmark.com E-Mail For technical sup...",""],
["detailed_error_log_history.htm","Detailed Error log history","Detailed Error log history Top Previous Next The detailed error log history can be opened from the ‘View / Error log file’ menu. It contains a rec...",""],
["disk_preferences.htm","Disk Preferences","Disk Preferences Top Previous Next Disk test preferences Partitioned drives they must be mounted before BurnInTest can test them, they also need t...",""],
["disk_test.htm","Hard Disk and Floppy Disk Test","Hard Disk and Floppy Disk Test Top Previous Next This suite contains a number of tests that exercise the mass storage units (Hard disk or otherwis...",""],
["duty_cycles.htm","Test Selection and Duty Cycles","Test Selection and Duty Cycles Top Previous Next From this window it is possible to configure the automatic stopping of tests, select the tests to...",""],
["entering_a_licence_key.htm","Entering A Licence Key","Entering A Licence Key Top Previous Next Copy your user name and key from the E-mail Select the entire key, including the -----START_OF_KEY----- a...",""],
["error_handling_preferences.htm","Error Handling Preferences","Error Handling Preferences Top Previous Next Action on Error When BurnInTest detects an error, three options are available. 1. Continue. The error...",""],
["example_ascii_log_file.htm","Example ASCII Log file","Example ASCII Log file Top Previous Next ASCII (Text) log files can be created using the logging option in the Test preferences dialog. The ASCII ...",""],
["fault_finding.htm","Fault finding","Fault finding Top Previous Next What follows are some hints on how go about finding the cause of particular system instability. We don’t want to t...",""],
["interpreting_the_results.htm","Interpreting the results","Interpreting the results Top Previous Next Status display In the main window there is a display that shows a summary of all the results of all the...",""],
["logging_preferences.htm","Logging Preferences","Logging Preferences Top Previous Next Automatic logging Logging to disk is switched on and off with the &#8220;Logging on&#8221; option. When disk logging is ...",""],
["loopback_plugs.htm","Making Loopback plugs","Making Loopback plugs Top Previous Next You can purchase high quality molded loop back plugs from PassMark or, for the serial and parallel version...",""],
["machine_identity.htm","Report Information (Machine ID and Notes)","Report Information (Machine Identity and Additional Notes) Top Previous Next The fields on this screen allow the entry of information related to t...",""],
["maintaining_multiple_test_configurations.htm","Maintaining Multiple Test Configurations","Maintaining Multiple Test Configurations Top Previous Next If you are in the business to testing many different computers then you may benefit fro...",""],
["maths_preferences.htm","CPU Math Preferences","CPU Math Preferences Top Previous Next Using the check boxes it is possible to select which maths tests will be performed and which ones will be s...",""],
["maths_tests.htm","CPU Maths Test","CPU Maths Test Top Previous Next The CPU test exercises and verifies a wide range of CPU instructions, at user specified loads. The user selectabl...",""],
["memory_preferences.htm","Memory Preferences","Memory Preferences Top Previous Next One of the test patterns can be selected for the test or the default option Cyclic can be used, which will cy...",""],
["memory_test.htm","Memory (RAM) test","Memory (RAM) test Top Previous Next Tests the Memory in the computer. The Memory test, tests the reliability of the RAM installed in the computer....",""],
["menu_options.htm","Menu Options","Menu Options Top Previous Next File Load Test Configuration A test configuration that has been previously saved to disk can be loaded using this m...",""],
["network_preferences.htm","Network Preferences","Network Preferences Top Previous Next Network addresses Up to 6 network addresses can be entered for the simultaneous testing of the connection to...",""],
["network_test.htm","Network Test","Network Test Top Previous Next The Network test tests your networking hardware and software. This is done by sending special ICMP_ECHO message usi...",""],
["other_useful_information.htm","Other Useful Information","Other Useful Information Top Previous Next Contacting PassMark Software System Requirements Example ASCII Log file Precautions for thorough and ca...",""],
["overview.htm","Introduction and Overview","Introduction and Overview Top Next BurnInTest is a software tool that allows all the major sub-systems of a computer to be simultaneously tested f...",""],
["parallel_port_loop_back_plug.htm","Parallel port loop back plug","Parallel Port Loopback plug Top Previous The parallel port on IBM compatible PCs have always used a DB-25 connector. However, over time several ch...",""],
["parallel_port_preferences.htm","Parallel Port Preferences","Parallel Port Preferences Top Previous Next Parallel port The communications port that will be used by the parallel port test, eg /dev/lp0, /dev/l...",""],
["parallel_test.htm","Parallel Port Test","Parallel Port Test Top Previous Next Tests the parallel communications port connected to the PC. The parallel port to be tested can be selected fr...",""],
["precautions_for_thorough_and_careful_testing.htm","Precautions for thorough and careful testing","Precautions for thorough and careful testing Top Previous Next For a hardware test to be useful several precautions need to be taken. Failure to t...",""],
["preparing_a_customer_test_cert.htm","Preparing a Customer Test Certificate","Preparing a Customer Test Certificate Top Previous Next A Test Certificate is a report targeted at your customer. It includes your company details...",""],
["pre_test_preferences.htm","Pre-test Preferences","Pre-test Preferences Top Previous Next You may specify the default behaviour of BurnInTest before it begins any test cycle. None (start immediatel...",""],
["purchase.htm","How to Purchase BurnInTest","How to Purchase BurnInTest Top Previous Next Price US Dollars: $49 (single user) See the PassMark website http://www.passmark.com/sales Please not...",""],
["quick_start.htm","Quick Start Guide","Quick Start - How to Start Testing Top Previous Next Here’s a summary of the steps to go through to start testing; 1. Use the Test Duty Cycles win...",""],
["scripting.htm","Scripting","Scripting Top Previous Next BurnInTest includes a simple scripting language that allows tests to be executed in a sequence. A PASS/FAIL indication...",""],
["serial_port_loopback_plug.htm","Serial port loopback plug","Serial Port Loopback Plug Top Previous Next The serial port on IBM compatible PCs conform to the RS232 electrical standard and use a male DB-9 con...",""],
["serial_port_preferences.htm","Serial Port Preferences","Serial Port Preferences Top Previous Next Adding a serial port To select a serial port for testing, select the COM port number (ttyS0-63) from the...",""],
["serial_test.htm","Serial Port Test","Serial Port Test Top Previous Next Tests the serial communications ports connected to the PC. Up to 64 serial ports may be tested simultaneously. ...",""],
["sound_preferences.htm","Sound Preferences","Sound Preferences Top Previous Next Max Distortion Select the maximum distortion allowable for the loopback test. The values available are between...",""],
["sound_test.htm","Sound Test","Sound Test Top Previous Next Sound loopback testing measures the distortion between audio input and audio output. Itinvolves connecting the audio ...",""],
["system_requirements.htm","System Requirements","System Requirements Top Previous Next Hardware requirements: - Intel and AMD compatible CPU. - Recommended 256MB of memory. - 15MB Disk space (mor...",""],
["test_descriptions.htm","Test Descriptions","Test Descriptions Top Previous Next Several tests are built into the software. Each of these tests contains one or more sub-tests designed to exer...",""],
["test_preferences.htm","Test Preferences","Test Preferences Top Previous Next Disk Preferences CPU Math Preferences Memory Preferences Network Preferences CD-ROM/DVD Preferences Parallel Po...",""],
["test_window_display.htm","Test Window display","Test Window display Top Previous Next Each test type has its own display window. The contents of the windows are described in the various tests. A...",""],
["usb_loopback_plugs.htm","USB Loopback Plugs","USB Loopback Plugs Top Previous Next USB 2.0 Loopback plugs can be used to help diagnose, troubleshoot and load test your PC’s USB 1.x and 2.0 por...",""],
["usb_test.htm","USB Test","USB Test Top Previous Next Tests the USB (Universal Serial Bus) communications ports connected to the PC. The number of USB devices to test can be...",""],
["usb_test_preferences.htm","USB Test Preferences","USB Test Preferences Top Previous Next Maximum number of USB ports This is the maximum number of USB plugs BurnInTest will attempt to connect to. ...",""],
["whats_new.htm","What&#39;s New","What&#39;s New Top Previous Next Please see our version history online at http://www.passmark.com/products/bitlinux_history.htm ",""]];
