components:
  bios:
    fw_date: 08/31/2017
    fw_date_verify: dmidecode -s bios-release-date
    fw_verify: dmidecode -s bios-version
    fw_version: 0.50
    post_action: reboot
    rollback_possible: False
    rollback_version: 
  bmc:
    fw_date: 08/31/2017
    fw_date_verify:
    fw_verify: ipmitool mc info | awk '/Firmware Revision/ { print $NF; }'
    fw_version: 0.50
    post_action:
    rollback_possible: True
    rollback_version: 0.41
  cpld_seq:
    fw_date: 07/10/2017
    fw_date_verify:
    fw_verify: 
    fw_version: 03
    post_action:
    rollback_possible: False
    rollback_version: 
  cpld_mgmt:
    fw_date: 07/10/2017
    fw_date_verify:
    fw_verify: 
    fw_version: 03
    post_action:
    rollback_possible: False
    rollback_version: 
fw_flash_command: /usr/bin/yes | ./update_all.sh
model: cannonball
vendor: <flex>
# must match list of components if more than 1.
update_order: bios,bmc,cpld_seq,cpld_mgmt
